name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission-glob:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: philips-forks/cmake-dependency-submission@main
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
  dependency-submission-configure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - run: cmake -S example -B build
      - uses: philips-forks/cmake-dependency-submission@main
        with:
          scanMode: 'configure'
          buildPath: 'build'
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
