name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission-glob:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: philips-forks/cmake-dependency-submission@main
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
  dependency-submission-configure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: cmake -S example -B build
      - uses: philips-forks/cmake-dependency-submission@main
        with:
          scanMode: 'configure'
          buildPath: 'build'
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
