name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Build and run tests
        run: npm rebuild && npm run all
