name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Build and run tests
        run: npm rebuild && npm run all
