name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Build and run tests
        run: npm rebuild && npm run all
